### ISSUE TITLE
Formát souřadnic 

### ISSUE THREAD

**Issue by MichalBryxi** [MichalBryxi/casosberne.cz#28]
U projektu jsou vidět souřadnice. Přidat písmenka N, E, W, S, aby bylo poznat že jde o GPS souřadnice.

**Comment by Geret** [comment]
Pro formát souřadnic lze použít standard WGS-84 v podobě N XX° XX.XXX E XXX° XX.XXX
Včetně značek pro stupně, teček a mezer.
Příklad: S 07° 54.968 W 014° 21.166 (souřadnice kešky na ostrově Ascension)

**Comment by MichalBryxi** [comment]
Ok, super. Po delsi elaboraci a hrani si souhlasim ze WGS-84 je spravna cesta. Pro jednoduchost jsem pouzil mapy.cz API, ktery danej format umi. Je malonko jinej (jina pozice pismenek), ale i google mapy i mapy.cz ho znaji. Ukazka:

<img width="422" alt="screen shot 2016-05-08 at 13 54 00" src="https://cloud.githubusercontent.com/assets/847473/15097917/9f2f403e-1524-11e6-8365-0e9d211e2050.png">

cc: @Geret

**Comment by MichalBryxi** [comment]
Damn, prohodil jsem sirku a delku ...
