### ISSUE TITLE
Copyright text

### ISSUE THREAD

**Issue by Geret** [MichalBryxi/casosberne.cz#32]
Je to úplná drobnost, ale když už je v zápatí stránky ten copyright, tak by tam mohlo být napsáno něco jiného, než "copyright text"

**Comment by MichalBryxi** [comment]
Nahled:

<img width="405" alt="screen shot 2016-05-08 at 12 19 20" src="https://cloud.githubusercontent.com/assets/847473/15097610/9f3a25be-1518-11e6-8c73-8ee1fccb62e7.png">
