### ISSUE TITLE
Řazení fotek v mobilním prohlížeči

### ISSUE THREAD

**Issue by Geret** [MichalBryxi/casosberne.cz#33]
V mobilním prohlížeči se fotky řadí pseudonáhodně, ne podle data pořízení. Fix it, please.
![mobilni_tajmlapster](https://cloud.githubusercontent.com/assets/7803542/14950699/1f8b13d2-1054-11e6-8a90-1e95e43013c9.jpg)

**Comment by MichalBryxi** [comment]
Mělo by být vyřešeno. cc: @Geret
