### ISSUE TITLE
Hezčí iframy s mapkami

### ISSUE THREAD

**Issue by Geret** [MichalBryxi/casosberne.cz#34]
aby to bylo hezci, bylo by fajn mit ty iframy s mapkama nejak lehce ohraniceny nebo aspon vystinovany a v pripade mapy projektu by nemusel ten iframe byt pres celej monitor
souvisí s: #28 #3

**Comment by MichalBryxi** [comment]
Ukazka stinu. Momentalne na stagingu: 

<img width="897" alt="screen shot 2016-05-08 at 15 41 36" src="https://cloud.githubusercontent.com/assets/847473/15098352/5c0cfa58-1533-11e6-9a42-cddd2bf1bc9b.png">
