### ISSUE TITLE
poloha projektu

### ISSUE THREAD

**Issue by Geret** [MichalBryxi/casosberne.cz#4]
Jako podnadpis u projektu bych pridal hyperlink v podobe GPS souradnic. Po rozkliknuti by se otevrela v novem panelu mapa s mistem.

**Comment by MichalBryxi** [comment]
@Geret mapy.cz, nebo Google mapy? :)

**Comment by Geret** [comment]
Mapy.cz

**Comment by MichalBryxi** [comment]
Záložka "Mapa": http://staging.casosberne.cz/#/project/1

**Comment by MichalBryxi** [comment]
- Známý bug: #25 
- Tenhle ticket bych už zavřel. Další regrese hlásit jako bugy s odkazem na tenhle ticket.
