### ISSUE TITLE
nový návod

### ISSUE THREAD

**Issue by Geret** [MichalBryxi/casosberne.cz#6]
Odsouhlasit podobu nového návodu, který se následně vytiskne, zalaminuje a umístí na stojan.
https://docs.google.com/document/d/1kqXNE8kBSKLLXT6SOHptg24IKPuqVojL3G5MXrmVt98/edit#heading=h.74f54na8lq5u

**Comment by MichalBryxi** [comment]
Upravil jsem pár věcí co se mi na návodu nezdály. Případně uprav zpátky, vytiskni a hurá!
